export default {
    //Ashen- user authentication actions
    USER_REGISTERED: 'USER_REGISTERED',
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    GET_REGISTER_RESPONSE_MESSAGE: 'GET_REGISTER_RESPONSE_MESSAGE',
    GET_ALL_USERS: 'GET_ALL_USERS',

    //Course Action
    GET_ALL_COURSES: 'GET_ALL_COURSES',
    GET_NEW_COURSE_RESPONSE_MESSAGE: 'GET_NEW_COURSE_RESPONSE_MESSAGE'
}